# Generated by Django 4.1.3 on 2022-11-15 05:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
